DROP TABLE IF EXISTS users;
CREATE TABLE `USERS` (
    `USER_ID` VARCHAR(20) NOT NULL
    ,`LOGIN_ID` VARCHAR(20) NOT NULL UNIQUE
    ,`PASSWORD` VARCHAR(256) NOT NULL UNIQUE
    ,`USER_GROUP` VARCHAR(20) NOT NULL
    ,CONSTRAINT PK_USER PRIMARY KEY (USER_ID)
);